# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import usuarios_pb2 as usuarios__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in usuarios_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsuarioServiceStub(object):
    """El Servicio gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearUsuario = channel.unary_unary(
                '/crud.UsuarioService/CrearUsuario',
                request_serializer=usuarios__pb2.UsuarioCreacion.SerializeToString,
                response_deserializer=usuarios__pb2.CrudResponse.FromString,
                _registered_method=True)
        self.LeerUsuarios = channel.unary_unary(
                '/crud.UsuarioService/LeerUsuarios',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=usuarios__pb2.UsuariosList.FromString,
                _registered_method=True)
        self.LeerUsuarioPorId = channel.unary_unary(
                '/crud.UsuarioService/LeerUsuarioPorId',
                request_serializer=usuarios__pb2.UsuarioId.SerializeToString,
                response_deserializer=usuarios__pb2.Usuario.FromString,
                _registered_method=True)
        self.ActualizarUsuario = channel.unary_unary(
                '/crud.UsuarioService/ActualizarUsuario',
                request_serializer=usuarios__pb2.Usuario.SerializeToString,
                response_deserializer=usuarios__pb2.CrudResponse.FromString,
                _registered_method=True)
        self.EliminarUsuario = channel.unary_unary(
                '/crud.UsuarioService/EliminarUsuario',
                request_serializer=usuarios__pb2.UsuarioId.SerializeToString,
                response_deserializer=usuarios__pb2.CrudResponse.FromString,
                _registered_method=True)


class UsuarioServiceServicer(object):
    """El Servicio gRPC
    """

    def CrearUsuario(self, request, context):
        """CREATE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeerUsuarios(self, request, context):
        """READ (Todos)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeerUsuarioPorId(self, request, context):
        """READ (Uno por ID)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarUsuario(self, request, context):
        """UPDATE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarUsuario(self, request, context):
        """DELETE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearUsuario,
                    request_deserializer=usuarios__pb2.UsuarioCreacion.FromString,
                    response_serializer=usuarios__pb2.CrudResponse.SerializeToString,
            ),
            'LeerUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.LeerUsuarios,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=usuarios__pb2.UsuariosList.SerializeToString,
            ),
            'LeerUsuarioPorId': grpc.unary_unary_rpc_method_handler(
                    servicer.LeerUsuarioPorId,
                    request_deserializer=usuarios__pb2.UsuarioId.FromString,
                    response_serializer=usuarios__pb2.Usuario.SerializeToString,
            ),
            'ActualizarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarUsuario,
                    request_deserializer=usuarios__pb2.Usuario.FromString,
                    response_serializer=usuarios__pb2.CrudResponse.SerializeToString,
            ),
            'EliminarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarUsuario,
                    request_deserializer=usuarios__pb2.UsuarioId.FromString,
                    response_serializer=usuarios__pb2.CrudResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crud.UsuarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crud.UsuarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsuarioService(object):
    """El Servicio gRPC
    """

    @staticmethod
    def CrearUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.UsuarioService/CrearUsuario',
            usuarios__pb2.UsuarioCreacion.SerializeToString,
            usuarios__pb2.CrudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeerUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.UsuarioService/LeerUsuarios',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            usuarios__pb2.UsuariosList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeerUsuarioPorId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.UsuarioService/LeerUsuarioPorId',
            usuarios__pb2.UsuarioId.SerializeToString,
            usuarios__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.UsuarioService/ActualizarUsuario',
            usuarios__pb2.Usuario.SerializeToString,
            usuarios__pb2.CrudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.UsuarioService/EliminarUsuario',
            usuarios__pb2.UsuarioId.SerializeToString,
            usuarios__pb2.CrudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
