# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuarios.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'usuarios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eusuarios.proto\x12\x04\x63rud\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x01\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x0e\n\x06genero\x18\x05 \x01(\t\x12\x1a\n\x12\x65stilos_preferidos\x18\x06 \x03(\t\x12\x17\n\x0fprendas_armario\x18\x07 \x03(\t\x12\x32\n\x0e\x66\x65\x63ha_registro\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nseguidores\x18\t \x03(\t\x12\x11\n\tsiguiendo\x18\n \x03(\t\"\xae\x01\n\x0fUsuarioCreacion\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0e\n\x06genero\x18\x04 \x01(\t\x12\x1a\n\x12\x65stilos_preferidos\x18\x05 \x03(\t\x12\x17\n\x0fprendas_armario\x18\x06 \x03(\t\x12\x12\n\nseguidores\x18\x07 \x03(\t\x12\x11\n\tsiguiendo\x18\x08 \x03(\t\"\x17\n\tUsuarioId\x12\n\n\x02id\x18\x01 \x01(\t\"E\n\x0c\x43rudResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0binserted_id\x18\x03 \x01(\t\"/\n\x0cUsuariosList\x12\x1f\n\x08usuarios\x18\x01 \x03(\x0b\x32\r.crud.Usuario2\xab\x02\n\x0eUsuarioService\x12\x39\n\x0c\x43rearUsuario\x12\x15.crud.UsuarioCreacion\x1a\x12.crud.CrudResponse\x12:\n\x0cLeerUsuarios\x12\x16.google.protobuf.Empty\x1a\x12.crud.UsuariosList\x12\x32\n\x10LeerUsuarioPorId\x12\x0f.crud.UsuarioId\x1a\r.crud.Usuario\x12\x36\n\x11\x41\x63tualizarUsuario\x12\r.crud.Usuario\x1a\x12.crud.CrudResponse\x12\x36\n\x0f\x45liminarUsuario\x12\x0f.crud.UsuarioId\x1a\x12.crud.CrudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuarios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIO']._serialized_start=87
  _globals['_USUARIO']._serialized_end=317
  _globals['_USUARIOCREACION']._serialized_start=320
  _globals['_USUARIOCREACION']._serialized_end=494
  _globals['_USUARIOID']._serialized_start=496
  _globals['_USUARIOID']._serialized_end=519
  _globals['_CRUDRESPONSE']._serialized_start=521
  _globals['_CRUDRESPONSE']._serialized_end=590
  _globals['_USUARIOSLIST']._serialized_start=592
  _globals['_USUARIOSLIST']._serialized_end=639
  _globals['_USUARIOSERVICE']._serialized_start=642
  _globals['_USUARIOSERVICE']._serialized_end=941
# @@protoc_insertion_point(module_scope)
